name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
      env:
        CI: true
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build
    - name: Clean install dependencies and build
      run: |
        yarn deploy
      env:
        CI: true
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
